# Add 'bar' label to any changes in foo/bar directory
bar:
  - changed-files:
    - any-glob-to-any-file: '**/*foo/*bar/**'

# Add 'foo' label to any changes in foo/foo directory
foo:
  - changed-files:
    - any-glob-to-any-file: '**/*foo/*foo/**'
