# Add 'bar' label to any changes in foo/bar directory
foobar:
  - changed-files:
    - any-glob-to-any-file: '*/*/*foobar/**'

# Add 'foo' label to any changes in foo/foo directory
foo:
  - changed-files:
    - any-glob-to-any-file: '*/*/*foo/**'
